<?php
// CHRONONAV_WEB_DOSS/pages/admin/manage_resets.php


// Set the current page variable for the sidebar to highlight the correct link
$current_page = 'manage_resets';

// Include necessary files
require_once '../../config/db_connect.php'; 

/** @var \mysqli $conn */ 

$reset_requests = [];
$message = '';
$message_type = '';

// 1. Fetch Active Password Reset Requests
$currentTime = date('Y-m-d H:i:s');

// SQL Query: Only selecting the necessary fields (user ID and email) since
// 'first_name' and 'last_name' were confirmed to be missing.
$sql = "
    SELECT 
        pr.id as reset_id,
        u.id as user_id,
        u.email,
        pr.expires_at,
        pr.created_at
    FROM 
        password_resets pr
    JOIN 
        users u ON pr.user_id = u.id
    WHERE 
        pr.expires_at > ?
    ORDER BY 
        pr.created_at DESC
";

if ($stmt = $conn->prepare($sql)) {
    $stmt->bind_param("s", $currentTime);
    $stmt->execute();
    $result = $stmt->get_result();
    
    while ($row = $result->fetch_assoc()) {
        $reset_requests[] = $row;
    }
    
    $stmt->close();
} else {
    $message = 'Database error: Could not load reset requests.';
    $message_type = 'danger';
    
    // Keeping debug output just in case
    $detailed_error = $conn->error;
    $message .= " <br> **MySQL Error:** " . htmlspecialchars($detailed_error); 
    error_log("Manage resets DB prepare failed: " . $conn->error);
}

// 2. Clear Request Logic
if (isset($_GET['action']) && $_GET['action'] == 'clear' && isset($_GET['user_id'])) {
    $clear_user_id = (int)$_GET['user_id'];
    
    $delete_stmt = $conn->prepare("DELETE FROM password_resets WHERE user_id = ?");
    if ($delete_stmt) {
        $delete_stmt->bind_param("i", $clear_user_id);
        if ($delete_stmt->execute()) {
            // Success, redirect to clean URL
            header("Location: manage_resets.php?status=cleared");
            exit;
        } else {
            $message = "Failed to clear the reset request: " . htmlspecialchars($conn->error);
            $message_type = 'danger';
        }
        $delete_stmt->close();
    }
}

// Check for successful clear operation redirect
if (isset($_GET['status']) && $_GET['status'] == 'cleared') {
    $message = "Reset request has been successfully cleared.";
    $message_type = 'success';
}


require_once '../../templates/admin/header_admin.php'; // HTML <head> & <body> start
require_once '../../templates/admin/sidenav_admin.php'; // The sidebar
?>

<div class="main-content-wrapper">
    <div class="container-fluid py-4">
        
        <header class="mb-4">
            <h1 class="h3">🔑 Password Reset Requests</h1>
            <p>Viewing all active, non-expired password reset links generated by users.</p>
        </header>

        <?php if ($message): ?>
            <div class="alert alert-<?= $message_type === 'success' ? 'success' : 'danger' ?>" role="alert">
                <?= $message ?>
            </div>
        <?php endif; ?>

        <?php if (empty($reset_requests)): ?>
            <div class="alert alert-info">
                <i class="fas fa-info-circle me-2"></i>There are currently no active password reset requests.
            </div>
        <?php else: ?>
            <div class="card shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">Active Requests (<?= count($reset_requests) ?>)</h5>
                    <div class="table-responsive">
                        <table class="table table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>User ID</th>
                                    <th>User Email</th>
                                    <th>Requested At</th>
                                    <th>Expires At</th>
                                    <th>Time Remaining</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($reset_requests as $request): 
                                    $remaining = strtotime($request['expires_at']) - time();
                                    $minutes = floor($remaining / 60);
                                    $seconds = $remaining % 60;
                                    $time_remaining = ($remaining > 0) ? "{$minutes} min {$seconds} sec" : 'EXPIRED';
                                    $badge_class = ($remaining > 0) ? 'bg-warning text-dark' : 'bg-secondary';
                                ?>
                                    <tr>
                                        <td><?= htmlspecialchars($request['user_id']) ?></td>
                                        <td><?= htmlspecialchars($request['email']) ?></td> 
                                        <td><?= date('Y-m-d H:i:s', strtotime($request['created_at'])) ?></td>
                                        <td><?= date('Y-m-d H:i:s', strtotime($request['expires_at'])) ?></td>
                                        <td><span class="badge <?= $badge_class ?>"><?= $time_remaining ?></span></td>
                                        <td>
                                            <a href="?action=clear&user_id=<?= $request['user_id'] ?>" 
                                               class="btn btn-sm btn-danger" 
                                               onclick="return confirm('Are you sure you want to manually clear this token?')">
                                                Clear Token
                                            </a>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        <?php endif; ?>

    </div>
</div>

<?php // require_once '../../includes/footer_admin.php'; // HTML </body> & </html> end ?>